# Generated by Django 5.2 on 2025-11-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_person_personaltransaction_delete_personalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('ADD', 'Add Money'), ('EXPENSE', 'Expense'), ('REFUND', 'Refund')], max_length=10),
        ),
    ]
