# Generated by Django 5.0 on 2026-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_personalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalrecord',
            name='type',
            field=models.CharField(choices=[('EXPENSE', 'Personal Expense'), ('LOAN', 'Personal Loan'), ('LENT', 'Money Lent'), ('BORROWED', 'Money Borrowed'), ('RECEIVED', 'Money Received Back'), ('PAID_BACK', 'Money Paid Back')], max_length=10),
        ),
    ]
